Update maven.yml

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -41,6 +41,16 @@ jobs:
         username: ${{secrets.EC2_USER_NAME}}
         key: ${{secrets.EC2_PRIVATE_KEY}}
         script: |
+         if ! command -v docker &> /dev/null
+            then
+              echo "Docker could not be found. Installing..."
+              curl -fsSL https://get.docker.com -o get-docker.sh
+              sh get-docker.sh
+              sudo usermod -aG docker $USER
+              newgrp docker
+            else
+              echo "Docker is already installed"
+            fi
           echo "SSH connection successful"
           docker login
           docker stop grocery-shop || true
